# Generated by Django 4.1 on 2022-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mySite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Homepage", max_length=255),
        ),
    ]
