# Generated by Django 4.1 on 2022-08-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mySite", "0004_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="Select", max_length=255),
        ),
    ]
